# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33c118df790114cc38b04b19e8b1518c0592e3ba704da3876805616a961cba852917e455fa7cb2309cdcf5e6b10fd942a963b97034d727995d722b09198fcfb1

test:
  secret_key_base: 7b2c0b77dc27f1490fbc11f8f93c4fb45c83bbfdb64452e34793d3dda2ba9fd72738831d7768f8834cfba6d66993100338c43871a2d10d3650bd67c20cf5a690

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
